{{- if .Values.metrics.prometheus.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "apache-nifi.fullname" . }}
{{- with .Values.metrics.prometheus.serviceMonitor.namespace }}
  namespace: {{ . }}
{{- end }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.metrics.prometheus.serviceMonitor.labels }}
{{ .Values.metrics.prometheus.serviceMonitor.labels | toYaml | indent 4 }}
{{- end }}
spec:
  endpoints:
  {{- if eq (include "apache-nifi.isInternalSecure" .) "false" }}
  - port: http
    scheme: http
  {{- else }}
  - port: https
    scheme: https
  {{- end }}
    path: /nifi-api/flow/metrics/prometheus
  {{- with .Values.metrics.prometheus.serviceMonitor.endpointContent }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metrics.prometheus.serviceMonitor.content }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "apache-nifi.name" . }}
      release: {{ .Release.Name }}
      metrics: "prometheus"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
{{- end }}
